describe("focus.nvim", function()
    local timer = require("focus.timer")
    local ui = require("focus.ui")

    describe("Time Formatting", function()
        it("should format minutes and seconds correctly", function()
            assert.are.same("25:00", timer.format_time(1500))
            assert.are.same("00:05", timer.format_time(5))
            assert.are.same("01:00", timer.format_time(60))
        end)
    end)

    describe("Progress Bar Generation", function()
        it("should return an empty bar at 0% progress", function()
            local bar = ui.generate_progress_bar(1500, 1500)
            assert.is_true(bar:match("0%%") ~= nil)
            assert.is_true(bar:match("░") ~= nil)
        end)
        it("should return a full bar at 100% progress", function()
            local bar = ui.generate_progress_bar(0, 1500)
            assert.is_true(bar:match("100%%") ~= nil)
            assert.is_true(bar:match("█") ~= nil)
        end)
        it("should handle division by zero gracefully", function()
            local bar = ui.generate_progress_bar(0, 0)
            assert.are.same("[░░░░░░░░░░░░░░░░░░░░] 0%", bar)
        end)
    end)
end)
