vim.api.nvim_create_user_command("FocusStart", function()
    require("focus.timer").start()
end, { desc = "Start the Timer" })
vim.api.nvim_create_user_command("FocusStop", function()
    require("focus.timer").stop()
end, { desc = "Stop the Timer" })
vim.api.nvim_create_user_command("FocusToggle", function()
    require("focus.timer").toggle_pause()
end, { desc = "Toggle Focus Timer" })
vim.api.nvim_create_user_command("FocusReset", function()
    require("focus.timer").reset()
end, { desc = "Reset Focus Timer" })
vim.api.nvim_create_user_command("FocusSkip", function()
    require("focus.timer").skip()
end, { desc = "Skip to Next State" })
vim.api.nvim_create_user_command("FocusMenu", function()
    require("focus.ui").menu()
end, { desc = "Open Focus Menu" })
